/*
 * fabi386: Generated Microcode ROM
 * Auto-generated by microcode_compiler.py — DO NOT EDIT
 * 142 mnemonics, 311 micro-ops
 */

`ifndef F386_MICROCODE_ROM_GEN_SV
`define F386_MICROCODE_ROM_GEN_SV

function automatic logic [47:0] microcode_rom_lookup(
    input logic [14:0] addr  // {is_0f, opcode[7:0], step[5:0]}
);
    case (addr)
        15'h09C0: microcode_rom_lookup = 48'h700001B00008;
        15'h0BC0: microcode_rom_lookup = 48'h700001C00008;
        15'h0DC0: microcode_rom_lookup = 48'h700001D00008;
        15'h0FC0: microcode_rom_lookup = 48'h700001E00008;
        15'h1800: microcode_rom_lookup = 48'h308008000004;
        15'h1801: microcode_rom_lookup = 48'h308408000004;
        15'h1802: microcode_rom_lookup = 48'h308808000004;
        15'h1803: microcode_rom_lookup = 48'h308C08000004;
        15'h1804: microcode_rom_lookup = 48'h309008000004;
        15'h1805: microcode_rom_lookup = 48'h309408000004;
        15'h1806: microcode_rom_lookup = 48'h309808000004;
        15'h1807: microcode_rom_lookup = 48'h309C0800000C;
        15'h1840: microcode_rom_lookup = 48'h20F008100004;
        15'h1841: microcode_rom_lookup = 48'h20D008100004;
        15'h1842: microcode_rom_lookup = 48'h20B008100004;
        15'h1843: microcode_rom_lookup = 48'h201008100004;
        15'h1844: microcode_rom_lookup = 48'h207008100004;
        15'h1845: microcode_rom_lookup = 48'h205008100004;
        15'h1846: microcode_rom_lookup = 48'h203008100004;
        15'h1847: microcode_rom_lookup = 48'h20100810000C;
        15'h1880: microcode_rom_lookup = 48'h200000000000;
        15'h1881: microcode_rom_lookup = 48'h200000000000;
        15'h1882: microcode_rom_lookup = 48'h700003300008;
        15'h18C0: microcode_rom_lookup = 48'h200000000000;
        15'h18C1: microcode_rom_lookup = 48'h700003C00000;
        15'h18C2: microcode_rom_lookup = 48'h300000000008;
        15'h1A40: microcode_rom_lookup = 48'h700001600000;
        15'h1A41: microcode_rom_lookup = 48'h700001800008;
        15'h1AC0: microcode_rom_lookup = 48'h700001600000;
        15'h1AC1: microcode_rom_lookup = 48'h700001800008;
        15'h1B00: microcode_rom_lookup = 48'h702001300000;
        15'h1B01: microcode_rom_lookup = 48'h704003900000;
        15'h1B02: microcode_rom_lookup = 48'h70E001200000;
        15'h1B03: microcode_rom_lookup = 48'h702001400000;
        15'h1B04: microcode_rom_lookup = 48'h700001500008;
        15'h1B40: microcode_rom_lookup = 48'h702001300000;
        15'h1B41: microcode_rom_lookup = 48'h704003900000;
        15'h1B42: microcode_rom_lookup = 48'h70E001200000;
        15'h1B43: microcode_rom_lookup = 48'h702001400000;
        15'h1B44: microcode_rom_lookup = 48'h700001500008;
        15'h1B80: microcode_rom_lookup = 48'h702001300000;
        15'h1B81: microcode_rom_lookup = 48'h70C001100000;
        15'h1B82: microcode_rom_lookup = 48'h704003A00000;
        15'h1B83: microcode_rom_lookup = 48'h702001400000;
        15'h1B84: microcode_rom_lookup = 48'h700001500008;
        15'h1BC0: microcode_rom_lookup = 48'h702001300000;
        15'h1BC1: microcode_rom_lookup = 48'h70C001100000;
        15'h1BC2: microcode_rom_lookup = 48'h704003A00000;
        15'h1BC3: microcode_rom_lookup = 48'h702001400000;
        15'h1BC4: microcode_rom_lookup = 48'h700001500008;
        15'h2180: microcode_rom_lookup = 48'h200000000004;
        15'h2181: microcode_rom_lookup = 48'h700002E00004;
        15'h2182: microcode_rom_lookup = 48'h30000000000C;
        15'h21C0: microcode_rom_lookup = 48'h200000000004;
        15'h21C1: microcode_rom_lookup = 48'h700002E00004;
        15'h21C2: microcode_rom_lookup = 48'h30000000000C;
        15'h2300: microcode_rom_lookup = 48'h700000200008;
        15'h2340: microcode_rom_lookup = 48'h030000000008;
        15'h2380: microcode_rom_lookup = 48'h200000000004;
        15'h2381: microcode_rom_lookup = 48'h70000010000C;
        15'h2400: microcode_rom_lookup = 48'h700000000008;
        15'h2600: microcode_rom_lookup = 48'h700002C00008;
        15'h2640: microcode_rom_lookup = 48'h704002D00008;
        15'h2680: microcode_rom_lookup = 48'h308008000004;
        15'h2681: microcode_rom_lookup = 48'h308008000004;
        15'h2682: microcode_rom_lookup = 48'h700000E0000C;
        15'h2700: microcode_rom_lookup = 48'h700000C00008;
        15'h2740: microcode_rom_lookup = 48'h700000D0000C;
        15'h2780: microcode_rom_lookup = 48'h700003700008;
        15'h27C0: microcode_rom_lookup = 48'h700003600008;
        15'h2900: microcode_rom_lookup = 48'h702001300000;
        15'h2901: microcode_rom_lookup = 48'h70C001100000;
        15'h2902: microcode_rom_lookup = 48'h70E001200000;
        15'h2903: microcode_rom_lookup = 48'h702001400000;
        15'h2904: microcode_rom_lookup = 48'h700001500008;
        15'h2940: microcode_rom_lookup = 48'h702001300000;
        15'h2941: microcode_rom_lookup = 48'h70C001100000;
        15'h2942: microcode_rom_lookup = 48'h70E001200000;
        15'h2943: microcode_rom_lookup = 48'h702001400000;
        15'h2944: microcode_rom_lookup = 48'h700001500008;
        15'h2980: microcode_rom_lookup = 48'h702001300000;
        15'h2981: microcode_rom_lookup = 48'h70C001100000;
        15'h2982: microcode_rom_lookup = 48'h70E001100000;
        15'h2983: microcode_rom_lookup = 48'h010000000000;
        15'h2984: microcode_rom_lookup = 48'h702001400000;
        15'h2985: microcode_rom_lookup = 48'h700001500008;
        15'h29C0: microcode_rom_lookup = 48'h702001300000;
        15'h29C1: microcode_rom_lookup = 48'h70C001100000;
        15'h29C2: microcode_rom_lookup = 48'h70E001100000;
        15'h29C3: microcode_rom_lookup = 48'h010000000000;
        15'h29C4: microcode_rom_lookup = 48'h702001400000;
        15'h29C5: microcode_rom_lookup = 48'h700001500008;
        15'h2A80: microcode_rom_lookup = 48'h702001300000;
        15'h2A81: microcode_rom_lookup = 48'h70E001200000;
        15'h2A82: microcode_rom_lookup = 48'h702001400000;
        15'h2A83: microcode_rom_lookup = 48'h700001500008;
        15'h2AC0: microcode_rom_lookup = 48'h702001300000;
        15'h2AC1: microcode_rom_lookup = 48'h70E001200000;
        15'h2AC2: microcode_rom_lookup = 48'h702001400000;
        15'h2AC3: microcode_rom_lookup = 48'h700001500008;
        15'h2B00: microcode_rom_lookup = 48'h702001300000;
        15'h2B01: microcode_rom_lookup = 48'h70C001100000;
        15'h2B02: microcode_rom_lookup = 48'h702001400000;
        15'h2B03: microcode_rom_lookup = 48'h700001500008;
        15'h2B40: microcode_rom_lookup = 48'h702001300000;
        15'h2B41: microcode_rom_lookup = 48'h70C001100000;
        15'h2B42: microcode_rom_lookup = 48'h702001400000;
        15'h2B43: microcode_rom_lookup = 48'h700001500008;
        15'h2B80: microcode_rom_lookup = 48'h702001300000;
        15'h2B81: microcode_rom_lookup = 48'h70E001100000;
        15'h2B82: microcode_rom_lookup = 48'h010000000000;
        15'h2B83: microcode_rom_lookup = 48'h702001400000;
        15'h2B84: microcode_rom_lookup = 48'h700001500008;
        15'h2BC0: microcode_rom_lookup = 48'h702001300000;
        15'h2BC1: microcode_rom_lookup = 48'h70E001100000;
        15'h2BC2: microcode_rom_lookup = 48'h010000000000;
        15'h2BC3: microcode_rom_lookup = 48'h702001400000;
        15'h2BC4: microcode_rom_lookup = 48'h700001500008;
        15'h3100: microcode_rom_lookup = 48'h200000000004;
        15'h3101: microcode_rom_lookup = 48'h200000000004;
        15'h3102: microcode_rom_lookup = 48'h700003B0000C;
        15'h3140: microcode_rom_lookup = 48'h200000000004;
        15'h3141: microcode_rom_lookup = 48'h200000000004;
        15'h3142: microcode_rom_lookup = 48'h700033B0000C;
        15'h3200: microcode_rom_lookup = 48'h309408000004;
        15'h3201: microcode_rom_lookup = 48'h03B000000004;
        15'h3202: microcode_rom_lookup = 48'h70A00310000C;
        15'h3240: microcode_rom_lookup = 48'h039400000000;
        15'h3241: microcode_rom_lookup = 48'h20B008100008;
        15'h32C0: microcode_rom_lookup = 48'h201008100004;
        15'h32C1: microcode_rom_lookup = 48'h201008100004;
        15'h32C2: microcode_rom_lookup = 48'h700000F0000C;
        15'h3340: microcode_rom_lookup = 48'h700000C00004;
        15'h3341: microcode_rom_lookup = 48'h700000A00004;
        15'h3342: microcode_rom_lookup = 48'h308008000004;
        15'h3343: microcode_rom_lookup = 48'h308008000004;
        15'h3344: microcode_rom_lookup = 48'h70000070000C;
        15'h33C0: microcode_rom_lookup = 48'h201008100004;
        15'h33C1: microcode_rom_lookup = 48'h201008100004;
        15'h33C2: microcode_rom_lookup = 48'h700000D00004;
        15'h33C3: microcode_rom_lookup = 48'h70000080000C;
        15'h3500: microcode_rom_lookup = 48'h700001F00008;
        15'h3540: microcode_rom_lookup = 48'h700002000008;
        15'h35C0: microcode_rom_lookup = 48'h700003400008;
        15'h3800: microcode_rom_lookup = 48'h702003500008;
        15'h3840: microcode_rom_lookup = 48'h702003500008;
        15'h3880: microcode_rom_lookup = 48'h702003500008;
        15'h3900: microcode_rom_lookup = 48'h700003900008;
        15'h3940: microcode_rom_lookup = 48'h700003900008;
        15'h3980: microcode_rom_lookup = 48'h700003A00008;
        15'h39C0: microcode_rom_lookup = 48'h700003A00008;
        15'h3B00: microcode_rom_lookup = 48'h704003900008;
        15'h3B40: microcode_rom_lookup = 48'h704003900008;
        15'h3B80: microcode_rom_lookup = 48'h704003A00008;
        15'h3BC0: microcode_rom_lookup = 48'h704003A00008;
        15'h3D00: microcode_rom_lookup = 48'h70000090000C;
        15'h3D40: microcode_rom_lookup = 48'h700004300008;
        15'h3E00: microcode_rom_lookup = 48'h700004100008;
        15'h3E40: microcode_rom_lookup = 48'h700004200008;
        15'h3E80: microcode_rom_lookup = 48'h700000A00008;
        15'h3EC0: microcode_rom_lookup = 48'h700000B00008;
        15'h3F00: microcode_rom_lookup = 48'h700004400008;
        15'h3F40: microcode_rom_lookup = 48'h700004500008;
        15'h4000: microcode_rom_lookup = 48'h200000000004;
        15'h4001: microcode_rom_lookup = 48'h70000010000C;
        15'h4040: microcode_rom_lookup = 48'h200000000004;
        15'h4041: microcode_rom_lookup = 48'h70000050000C;
        15'h4080: microcode_rom_lookup = 48'h200000000000;
        15'h4081: microcode_rom_lookup = 48'h700003D00008;
        15'h40C0: microcode_rom_lookup = 48'h200000000000;
        15'h40C1: microcode_rom_lookup = 48'h700003E00008;
        15'h4800: microcode_rom_lookup = 48'h70000030000C;
        15'h4880: microcode_rom_lookup = 48'h70000040000C;
        15'h6400: microcode_rom_lookup = 48'h700003800008;
        15'h6440: microcode_rom_lookup = 48'h700003800008;
        15'h6480: microcode_rom_lookup = 48'h700003800008;
        15'h64C0: microcode_rom_lookup = 48'h700003800008;
        15'h6500: microcode_rom_lookup = 48'h700003800008;
        15'h6540: microcode_rom_lookup = 48'h700003800008;
        15'h6580: microcode_rom_lookup = 48'h700003800008;
        15'h65C0: microcode_rom_lookup = 48'h700003800008;
        15'h6600: microcode_rom_lookup = 48'h700003800008;
        15'h6640: microcode_rom_lookup = 48'h700003800008;
        15'h6680: microcode_rom_lookup = 48'h700003800008;
        15'h66C0: microcode_rom_lookup = 48'h700003800008;
        15'h6700: microcode_rom_lookup = 48'h700003800008;
        15'h6740: microcode_rom_lookup = 48'h700003800008;
        15'h6780: microcode_rom_lookup = 48'h700003800008;
        15'h67C0: microcode_rom_lookup = 48'h700003800008;
        15'h68C0: microcode_rom_lookup = 48'h200000000000;
        15'h68C1: microcode_rom_lookup = 48'h700002100008;
        15'h6900: microcode_rom_lookup = 48'h700002700008;
        15'h6940: microcode_rom_lookup = 48'h700002700008;
        15'h6AC0: microcode_rom_lookup = 48'h200000000000;
        15'h6AC1: microcode_rom_lookup = 48'h700002200000;
        15'h6AC2: microcode_rom_lookup = 48'h300000000008;
        15'h6B00: microcode_rom_lookup = 48'h700002800008;
        15'h6B40: microcode_rom_lookup = 48'h700002800008;
        15'h6BC0: microcode_rom_lookup = 48'h700001600000;
        15'h6BC1: microcode_rom_lookup = 48'h700001800008;
        15'h6C00: microcode_rom_lookup = 48'h200000000004;
        15'h6C01: microcode_rom_lookup = 48'h700002F00004;
        15'h6C02: microcode_rom_lookup = 48'h30000000000C;
        15'h6C40: microcode_rom_lookup = 48'h200000000004;
        15'h6C41: microcode_rom_lookup = 48'h700002F00004;
        15'h6C42: microcode_rom_lookup = 48'h30000000000C;
        15'h6C80: microcode_rom_lookup = 48'h200000000004;
        15'h6C81: microcode_rom_lookup = 48'h200000000004;
        15'h6C82: microcode_rom_lookup = 48'h700003B0000C;
        15'h6CC0: microcode_rom_lookup = 48'h200000000000;
        15'h6CC1: microcode_rom_lookup = 48'h700002300000;
        15'h6CC2: microcode_rom_lookup = 48'h300000000008;
        15'h6D00: microcode_rom_lookup = 48'h200000000004;
        15'h6D01: microcode_rom_lookup = 48'h200000000004;
        15'h6D02: microcode_rom_lookup = 48'h700003B0000C;
        15'h6D40: microcode_rom_lookup = 48'h200000000004;
        15'h6D41: microcode_rom_lookup = 48'h200000000004;
        15'h6D42: microcode_rom_lookup = 48'h700003B0000C;
        15'h6D80: microcode_rom_lookup = 48'h700002A00008;
        15'h6DC0: microcode_rom_lookup = 48'h700002A00008;
        15'h6EC0: microcode_rom_lookup = 48'h200000000000;
        15'h6EC1: microcode_rom_lookup = 48'h700002400000;
        15'h6EC2: microcode_rom_lookup = 48'h300000000008;
        15'h6F00: microcode_rom_lookup = 48'h700002500008;
        15'h6F40: microcode_rom_lookup = 48'h700002600008;
        15'h6F80: microcode_rom_lookup = 48'h700002B00008;
        15'h6FC0: microcode_rom_lookup = 48'h700002B00008;
        15'h7000: microcode_rom_lookup = 48'h200000000004;
        15'h7001: microcode_rom_lookup = 48'h700003000004;
        15'h7002: microcode_rom_lookup = 48'h30000000000C;
        15'h7040: microcode_rom_lookup = 48'h200000000004;
        15'h7041: microcode_rom_lookup = 48'h700003000004;
        15'h7042: microcode_rom_lookup = 48'h30000000000C;
        15'h7200: microcode_rom_lookup = 48'h700002900008;
        15'h7400: microcode_rom_lookup = 48'h200000000000;
        15'h7401: microcode_rom_lookup = 48'h700001600000;
        15'h7402: microcode_rom_lookup = 48'h700001800008;
        15'h7440: microcode_rom_lookup = 48'h200000000000;
        15'h7441: microcode_rom_lookup = 48'h700001600000;
        15'h7442: microcode_rom_lookup = 48'h700001800008;
        15'h7480: microcode_rom_lookup = 48'h200000000000;
        15'h7481: microcode_rom_lookup = 48'h700001700000;
        15'h7482: microcode_rom_lookup = 48'h700001900000;
        15'h7483: microcode_rom_lookup = 48'h700001A00008;
        15'h74C0: microcode_rom_lookup = 48'h200000000000;
        15'h74C1: microcode_rom_lookup = 48'h700001700000;
        15'h74C2: microcode_rom_lookup = 48'h700001900000;
        15'h74C3: microcode_rom_lookup = 48'h700001A00008;
        15'h7500: microcode_rom_lookup = 48'h200000000000;
        15'h7501: microcode_rom_lookup = 48'h700001600000;
        15'h7502: microcode_rom_lookup = 48'h704001800008;
        15'h7540: microcode_rom_lookup = 48'h200000000000;
        15'h7541: microcode_rom_lookup = 48'h700001600000;
        15'h7542: microcode_rom_lookup = 48'h704001800008;
        15'h7580: microcode_rom_lookup = 48'h200000000000;
        15'h7581: microcode_rom_lookup = 48'h700001700000;
        15'h7582: microcode_rom_lookup = 48'h700001900000;
        15'h7583: microcode_rom_lookup = 48'h704001A00008;
        15'h75C0: microcode_rom_lookup = 48'h200000000000;
        15'h75C1: microcode_rom_lookup = 48'h700001700000;
        15'h75C2: microcode_rom_lookup = 48'h700001900000;
        15'h75C3: microcode_rom_lookup = 48'h704001A00008;
        15'h7600: microcode_rom_lookup = 48'h200000000000;
        15'h7601: microcode_rom_lookup = 48'h0B0000000000;
        15'h7602: microcode_rom_lookup = 48'h300000000008;
        15'h7640: microcode_rom_lookup = 48'h200000000000;
        15'h7641: microcode_rom_lookup = 48'h0A0000000000;
        15'h7642: microcode_rom_lookup = 48'h300000000008;
        15'h7680: microcode_rom_lookup = 48'h200000000000;
        15'h7681: microcode_rom_lookup = 48'h700002100008;
        15'h76C0: microcode_rom_lookup = 48'h200000000000;
        15'h76C1: microcode_rom_lookup = 48'h700002200000;
        15'h76C2: microcode_rom_lookup = 48'h300000000008;
        15'h7700: microcode_rom_lookup = 48'h200000000000;
        15'h7701: microcode_rom_lookup = 48'h700002300000;
        15'h7702: microcode_rom_lookup = 48'h300000000008;
        15'h7740: microcode_rom_lookup = 48'h200000000000;
        15'h7741: microcode_rom_lookup = 48'h700002400000;
        15'h7742: microcode_rom_lookup = 48'h300000000008;
        15'h7780: microcode_rom_lookup = 48'h200000000000;
        15'h7781: microcode_rom_lookup = 48'h0C0000000000;
        15'h7782: microcode_rom_lookup = 48'h300000000008;
        15'h77C0: microcode_rom_lookup = 48'h200000000000;
        15'h77C1: microcode_rom_lookup = 48'h0D0000000000;
        15'h77C2: microcode_rom_lookup = 48'h300000000008;
        15'h7800: microcode_rom_lookup = 48'h200000000000;
        15'h7801: microcode_rom_lookup = 48'h308008000000;
        15'h7802: microcode_rom_lookup = 48'h030000000008;
        15'h7840: microcode_rom_lookup = 48'h200000000004;
        15'h7841: microcode_rom_lookup = 48'h200000000004;
        15'h7842: microcode_rom_lookup = 48'h308008000004;
        15'h7843: microcode_rom_lookup = 48'h308008000004;
        15'h7844: microcode_rom_lookup = 48'h700000E0000C;
        15'h7880: microcode_rom_lookup = 48'h200000000000;
        15'h7881: microcode_rom_lookup = 48'h030000000008;
        15'h78C0: microcode_rom_lookup = 48'h200000000004;
        15'h78C1: microcode_rom_lookup = 48'h200000000004;
        15'h78C2: microcode_rom_lookup = 48'h700000E0000C;
        15'h7900: microcode_rom_lookup = 48'h200000000000;
        15'h7901: microcode_rom_lookup = 48'h308008000008;
        15'h7940: microcode_rom_lookup = 48'h200000000000;
        15'h7941: microcode_rom_lookup = 48'h700003F00008;
        15'h7980: microcode_rom_lookup = 48'h200000000000;
        15'h7981: microcode_rom_lookup = 48'h700004000008;
        15'h79C0: microcode_rom_lookup = 48'h700000600008;
        15'h7A00: microcode_rom_lookup = 48'h700000600008;
        15'h7A40: microcode_rom_lookup = 48'h700000200008;
        15'h7A80: microcode_rom_lookup = 48'h700000200008;
        15'h7AC0: microcode_rom_lookup = 48'h700000400008;
        15'h7B00: microcode_rom_lookup = 48'h200000000004;
        15'h7B01: microcode_rom_lookup = 48'h70000030000C;
        `ifdef VERILATOR
        // CPUID (0F A2): 3 ALU micro-ops writing EAX, EBX, ECX
        15'h6880: microcode_rom_lookup = 48'h100000000110;  // step 0: ALU_IMM dest=EAX imm=0x0011
        15'h6881: microcode_rom_lookup = 48'h10600C000220;  // step 1: ALU_IMM dest=EBX imm=0x0022
        15'h6882: microcode_rom_lookup = 48'h102004000338;  // step 2: ALU_IMM dest=ECX imm=0x0033 is_last
        // Test opcode 0xD6: PUSH EAX → POP EBX (microcode mem bring-up)
        15'h3580: microcode_rom_lookup = 48'h308008000000;  // step 0: PUSH EAX (UCMD_PUSH_PRE)
        15'h3581: microcode_rom_lookup = 48'h207008100008;  // step 1: POP EBX (UCMD_POP_POST, is_last)
        `endif
        default:    microcode_rom_lookup = 48'h000000000000;
    endcase
endfunction

function automatic logic [5:0] microcode_max_step(
    input logic [7:0] opcode,
    input logic       is_0f
);
    case ({is_0f, opcode})
        9'h027: microcode_max_step = 6'd1;
        9'h02F: microcode_max_step = 6'd1;
        9'h037: microcode_max_step = 6'd1;
        9'h03F: microcode_max_step = 6'd1;
        9'h060: microcode_max_step = 6'd8;
        9'h061: microcode_max_step = 6'd8;
        9'h062: microcode_max_step = 6'd3;
        9'h063: microcode_max_step = 6'd3;
        9'h069: microcode_max_step = 6'd2;
        9'h06B: microcode_max_step = 6'd2;
        9'h06C: microcode_max_step = 6'd5;
        9'h06D: microcode_max_step = 6'd5;
        9'h06E: microcode_max_step = 6'd5;
        9'h06F: microcode_max_step = 6'd5;
        9'h086: microcode_max_step = 6'd3;
        9'h087: microcode_max_step = 6'd3;
        9'h08C: microcode_max_step = 6'd1;
        9'h08D: microcode_max_step = 6'd1;
        9'h08E: microcode_max_step = 6'd2;
        9'h090: microcode_max_step = 6'd1;
        9'h098: microcode_max_step = 6'd1;
        9'h099: microcode_max_step = 6'd1;
        9'h09A: microcode_max_step = 6'd3;
        9'h09C: microcode_max_step = 6'd1;
        9'h09D: microcode_max_step = 6'd1;
        9'h09E: microcode_max_step = 6'd1;
        9'h09F: microcode_max_step = 6'd1;
        9'h0A4: microcode_max_step = 6'd5;
        9'h0A5: microcode_max_step = 6'd5;
        9'h0A6: microcode_max_step = 6'd6;
        9'h0A7: microcode_max_step = 6'd6;
        9'h0AA: microcode_max_step = 6'd4;
        9'h0AB: microcode_max_step = 6'd4;
        9'h0AC: microcode_max_step = 6'd4;
        9'h0AD: microcode_max_step = 6'd4;
        9'h0AE: microcode_max_step = 6'd5;
        9'h0AF: microcode_max_step = 6'd5;
        9'h0C4: microcode_max_step = 6'd3;
        9'h0C5: microcode_max_step = 6'd3;
        9'h0C8: microcode_max_step = 6'd3;
        9'h0C9: microcode_max_step = 6'd2;
        9'h0CB: microcode_max_step = 6'd3;
        9'h0CD: microcode_max_step = 6'd5;
        9'h0CF: microcode_max_step = 6'd4;
        9'h0D4: microcode_max_step = 6'd1;
        9'h0D5: microcode_max_step = 6'd1;
        `ifdef VERILATOR
        9'h0D6: microcode_max_step = 6'd2;  // Test opcode: PUSH+POP
        `endif
        9'h0D7: microcode_max_step = 6'd1;
        9'h0E0: microcode_max_step = 6'd1;
        9'h0E1: microcode_max_step = 6'd1;
        9'h0E2: microcode_max_step = 6'd1;
        9'h0E4: microcode_max_step = 6'd1;
        9'h0E5: microcode_max_step = 6'd1;
        9'h0E6: microcode_max_step = 6'd1;
        9'h0E7: microcode_max_step = 6'd1;
        9'h0EC: microcode_max_step = 6'd1;
        9'h0ED: microcode_max_step = 6'd1;
        9'h0EE: microcode_max_step = 6'd1;
        9'h0EF: microcode_max_step = 6'd1;
        9'h0F4: microcode_max_step = 6'd1;
        9'h0F5: microcode_max_step = 6'd1;
        9'h0F8: microcode_max_step = 6'd1;
        9'h0F9: microcode_max_step = 6'd1;
        9'h0FA: microcode_max_step = 6'd1;
        9'h0FB: microcode_max_step = 6'd1;
        9'h0FC: microcode_max_step = 6'd1;
        9'h0FD: microcode_max_step = 6'd1;
        9'h100: microcode_max_step = 6'd2;
        9'h101: microcode_max_step = 6'd2;
        9'h102: microcode_max_step = 6'd2;
        9'h103: microcode_max_step = 6'd2;
        9'h120: microcode_max_step = 6'd1;
        9'h122: microcode_max_step = 6'd1;
        9'h190: microcode_max_step = 6'd1;
        9'h191: microcode_max_step = 6'd1;
        9'h192: microcode_max_step = 6'd1;
        9'h193: microcode_max_step = 6'd1;
        9'h194: microcode_max_step = 6'd1;
        9'h195: microcode_max_step = 6'd1;
        9'h196: microcode_max_step = 6'd1;
        9'h197: microcode_max_step = 6'd1;
        9'h198: microcode_max_step = 6'd1;
        9'h199: microcode_max_step = 6'd1;
        9'h19A: microcode_max_step = 6'd1;
        9'h19B: microcode_max_step = 6'd1;
        9'h19C: microcode_max_step = 6'd1;
        9'h19D: microcode_max_step = 6'd1;
        9'h19E: microcode_max_step = 6'd1;
        9'h19F: microcode_max_step = 6'd1;
        `ifdef VERILATOR
        9'h1A2: microcode_max_step = 6'd3;  // CPUID
        `endif
        9'h1A3: microcode_max_step = 6'd2;
        9'h1A4: microcode_max_step = 6'd1;
        9'h1A5: microcode_max_step = 6'd1;
        9'h1AB: microcode_max_step = 6'd3;
        9'h1AC: microcode_max_step = 6'd1;
        9'h1AD: microcode_max_step = 6'd1;
        9'h1AF: microcode_max_step = 6'd2;
        9'h1B0: microcode_max_step = 6'd3;
        9'h1B1: microcode_max_step = 6'd3;
        9'h1B2: microcode_max_step = 6'd3;
        9'h1B3: microcode_max_step = 6'd3;
        9'h1B4: microcode_max_step = 6'd3;
        9'h1B5: microcode_max_step = 6'd3;
        9'h1B6: microcode_max_step = 6'd1;
        9'h1B7: microcode_max_step = 6'd1;
        9'h1BB: microcode_max_step = 6'd3;
        9'h1BC: microcode_max_step = 6'd1;
        9'h1BD: microcode_max_step = 6'd1;
        9'h1BE: microcode_max_step = 6'd1;
        9'h1BF: microcode_max_step = 6'd1;
        9'h1C0: microcode_max_step = 6'd3;
        9'h1C1: microcode_max_step = 6'd3;
        9'h1C8: microcode_max_step = 6'd1;
        9'h1D0: microcode_max_step = 6'd3;
        9'h1D1: microcode_max_step = 6'd3;
        9'h1D2: microcode_max_step = 6'd4;
        9'h1D3: microcode_max_step = 6'd4;
        9'h1D4: microcode_max_step = 6'd3;
        9'h1D5: microcode_max_step = 6'd3;
        9'h1D6: microcode_max_step = 6'd4;
        9'h1D7: microcode_max_step = 6'd4;
        9'h1D8: microcode_max_step = 6'd3;
        9'h1D9: microcode_max_step = 6'd3;
        9'h1DA: microcode_max_step = 6'd2;
        9'h1DB: microcode_max_step = 6'd3;
        9'h1DC: microcode_max_step = 6'd3;
        9'h1DD: microcode_max_step = 6'd3;
        9'h1DE: microcode_max_step = 6'd3;
        9'h1DF: microcode_max_step = 6'd3;
        9'h1E0: microcode_max_step = 6'd3;
        9'h1E1: microcode_max_step = 6'd5;
        9'h1E2: microcode_max_step = 6'd2;
        9'h1E3: microcode_max_step = 6'd3;
        9'h1E4: microcode_max_step = 6'd2;
        9'h1E5: microcode_max_step = 6'd2;
        9'h1E6: microcode_max_step = 6'd2;
        9'h1E7: microcode_max_step = 6'd1;
        9'h1E8: microcode_max_step = 6'd1;
        9'h1E9: microcode_max_step = 6'd1;
        9'h1EA: microcode_max_step = 6'd1;
        9'h1EB: microcode_max_step = 6'd1;
        9'h1EC: microcode_max_step = 6'd2;
        default: microcode_max_step = 6'd1;
    endcase
endfunction

function automatic logic microcode_is_atomic(
    input logic [7:0] opcode,
    input logic       is_0f
);
    case ({is_0f, opcode})
        9'h060: microcode_is_atomic = 1'b1;
        9'h061: microcode_is_atomic = 1'b1;
        9'h086: microcode_is_atomic = 1'b1;
        9'h087: microcode_is_atomic = 1'b1;
        9'h08E: microcode_is_atomic = 1'b1;
        9'h09A: microcode_is_atomic = 1'b1;
        9'h09D: microcode_is_atomic = 1'b1;
        9'h0C4: microcode_is_atomic = 1'b1;
        9'h0C5: microcode_is_atomic = 1'b1;
        9'h0C8: microcode_is_atomic = 1'b1;
        9'h0CB: microcode_is_atomic = 1'b1;
        9'h0CD: microcode_is_atomic = 1'b1;
        9'h0CF: microcode_is_atomic = 1'b1;
        9'h0F4: microcode_is_atomic = 1'b1;
        9'h100: microcode_is_atomic = 1'b1;
        9'h101: microcode_is_atomic = 1'b1;
        9'h120: microcode_is_atomic = 1'b1;
        9'h122: microcode_is_atomic = 1'b1;
        `ifdef VERILATOR
        9'h1A2: microcode_is_atomic = 1'b1;  // CPUID
        `endif
        9'h1B0: microcode_is_atomic = 1'b1;
        9'h1B1: microcode_is_atomic = 1'b1;
        9'h1B2: microcode_is_atomic = 1'b1;
        9'h1B4: microcode_is_atomic = 1'b1;
        9'h1B5: microcode_is_atomic = 1'b1;
        9'h1C0: microcode_is_atomic = 1'b1;
        9'h1C1: microcode_is_atomic = 1'b1;
        9'h1E1: microcode_is_atomic = 1'b1;
        9'h1E3: microcode_is_atomic = 1'b1;
        9'h1EC: microcode_is_atomic = 1'b1;
        default: microcode_is_atomic = 1'b0;
    endcase
endfunction

// Group opcode remap: {is_0f, opcode, modrm_reg} → virtual opcode in 0F space
// Returns {remap_is_0f, remap_opcode} — 9 bits
function automatic logic [8:0] microcode_group_remap(
    input logic [7:0] opcode,
    input logic       is_0f,
    input logic [2:0] modrm_reg
);
    case ({is_0f, opcode, modrm_reg})
        12'h7B4: microcode_group_remap = 9'h1D0;  // 0xf6/4 → 0F 0xd0
        12'h7B5: microcode_group_remap = 9'h1D1;  // 0xf6/5 → 0F 0xd1
        12'h7B6: microcode_group_remap = 9'h1D2;  // 0xf6/6 → 0F 0xd2
        12'h7B7: microcode_group_remap = 9'h1D3;  // 0xf6/7 → 0F 0xd3
        12'h7BA: microcode_group_remap = 9'h1D9;  // 0xf7/2 → 0F 0xd9
        12'h7BB: microcode_group_remap = 9'h1D8;  // 0xf7/3 → 0F 0xd8
        12'h7BC: microcode_group_remap = 9'h1D4;  // 0xf7/4 → 0F 0xd4
        12'h7BD: microcode_group_remap = 9'h1D5;  // 0xf7/5 → 0F 0xd5
        12'h7BE: microcode_group_remap = 9'h1D6;  // 0xf7/6 → 0F 0xd6
        12'h7BF: microcode_group_remap = 9'h1D7;  // 0xf7/7 → 0F 0xd7
        12'h7F0: microcode_group_remap = 9'h1DE;  // 0xfe/0 → 0F 0xde
        12'h7F1: microcode_group_remap = 9'h1DF;  // 0xfe/1 → 0F 0xdf
        12'h7FA: microcode_group_remap = 9'h1E0;  // 0xff/2 → 0F 0xe0
        12'h7FB: microcode_group_remap = 9'h1E1;  // 0xff/3 → 0F 0xe1
        12'h7FC: microcode_group_remap = 9'h1E2;  // 0xff/4 → 0F 0xe2
        12'h7FD: microcode_group_remap = 9'h1E3;  // 0xff/5 → 0F 0xe3
        12'h7FE: microcode_group_remap = 9'h1E4;  // 0xff/6 → 0F 0xe4
        12'h800: microcode_group_remap = 9'h1E9;  // 0x00/0 → 0F 0xe9
        12'h801: microcode_group_remap = 9'h1EA;  // 0x00/1 → 0F 0xea
        12'h804: microcode_group_remap = 9'h1E5;  // 0x00/4 → 0F 0xe5
        12'h805: microcode_group_remap = 9'h1E6;  // 0x00/5 → 0F 0xe6
        12'h808: microcode_group_remap = 9'h1E7;  // 0x01/0 → 0F 0xe7
        12'h809: microcode_group_remap = 9'h1E8;  // 0x01/1 → 0F 0xe8
        12'h80C: microcode_group_remap = 9'h1EB;  // 0x01/4 → 0F 0xeb
        12'h80E: microcode_group_remap = 9'h1EC;  // 0x01/6 → 0F 0xec
        12'hDD4: microcode_group_remap = 9'h1DA;  // 0xba/4 → 0F 0xda
        12'hDD5: microcode_group_remap = 9'h1DB;  // 0xba/5 → 0F 0xdb
        12'hDD6: microcode_group_remap = 9'h1DC;  // 0xba/6 → 0F 0xdc
        12'hDD7: microcode_group_remap = 9'h1DD;  // 0xba/7 → 0F 0xdd
        default: microcode_group_remap = {is_0f, opcode};
    endcase
endfunction

`endif
