/*
 * fabi386: Microcode Sequencer (v2.0)
 * -------------------------------------
 * Steps through micro-op sequences for complex x86 instructions.
 * Interfaces between the decode stage (which identifies microcoded
 * instructions) and the execute stage (which processes individual
 * micro-ops).
 *
 * Architecture:
 *   - Indexed ROM lookup: {is_0f, opcode[7:0], step[5:0]} → 48-bit uop
 *   - Group opcode remap: F6/F7/FE/FF + modrm_reg → virtual opcode
 *   - FSM steps through sequence until is_last flag
 *   - Atomic sequences block interrupts
 *   - REP prefix: loops back to step 0 until ECX==0 or ZF mismatch
 *
 * v2.0: Added group opcode remap, REP prefix support, REP_YIELD
 *       for interrupt-safe string operation loops.
 *
 * Reference: ao486 pipeline/microcode.v, 80x86 microcode/
 */

import f386_pkg::*;

`include "f386_microcode_defs.svh"
`include "f386_microcode_rom_gen.sv"

module f386_microcode_sequencer (
    input  logic         clk,
    input  logic         rst_n,
    input  logic         flush,

    // --- Trigger Interface (from decode/dispatch) ---
    input  logic         start,           // Start microcode sequence
    input  logic [7:0]   opcode,          // x86 opcode
    input  logic [7:0]   opcode_ext,      // 0F extension opcode
    input  logic         is_0f_prefix,    // 0F prefix present
    input  logic         is_rep_prefix,   // REP/REPE/REPNE prefix present
    input  logic         is_repne,        // 1 = REPNE (F2), 0 = REP/REPE (F3)
    input  logic         is_32bit,        // 32-bit operand size
    input  logic [2:0]   modrm_reg,       // ModRM.reg field
    input  logic [31:0]  instr_pc,        // PC of microcoded instruction

    // --- Micro-op Output (to execute stage) ---
    output logic         uop_valid,       // Micro-op ready
    output logic [47:0]  uop_data,        // Raw 48-bit micro-op
    output op_type_t     uop_op_type,     // Decoded operation type
    output logic [3:0]   uop_alu_op,      // ALU operation
    output logic [2:0]   uop_dest_reg,    // Destination register
    output logic [2:0]   uop_src_a_reg,   // Source A register
    output logic [2:0]   uop_src_b_reg,   // Source B register
    output logic [2:0]   uop_seg_reg,     // Segment register
    output logic [7:0]   uop_special_cmd, // Special command
    output logic [15:0]  uop_immediate,   // Immediate value
    output logic         uop_is_last,     // Last micro-op in sequence
    output logic         uop_is_atomic,   // Atomic (non-interruptible)

    // --- Flow Control ---
    input  logic         exec_ack,        // Execute consumed the micro-op
    output logic         busy,            // Sequencer is active
    output logic         block_interrupt,  // Atomic sequence: don't take interrupts

    // --- REP Status (from execute stage) ---
    input  logic         rep_ecx_zero,    // ECX == 0 (after decrement)
    input  logic         rep_zf_value     // Current ZF value (for REPE/REPNE)
);

    // =========================================================
    // State Machine
    // =========================================================
    typedef enum logic [2:0] {
        SEQ_IDLE      = 3'd0,
        SEQ_ACTIVE    = 3'd1,
        SEQ_STALL     = 3'd2,  // Waiting for exec_ack
        SEQ_REP_CHECK = 3'd3   // REP_YIELD: check loop continuation
    } seq_state_t;

    seq_state_t state;

    // Registered sequence parameters
    logic [7:0]  r_opcode;
    logic        r_is_0f;
    logic [5:0]  r_step;
    logic [5:0]  r_max_step;
    logic        r_atomic;
    logic        r_is_rep;
    logic        r_is_repne;

    assign busy            = (state != SEQ_IDLE);
    assign block_interrupt = busy && r_atomic;

    // =========================================================
    // Group Opcode Remap
    // =========================================================
    // For group opcodes (F6/F7/FE/FF, 0F 00/01/BA), the modrm_reg
    // field selects the sub-operation. The remap function maps
    // {is_0f, opcode, modrm_reg} → {eff_is_0f, eff_opcode} using
    // a virtual opcode table generated by the compiler.
    logic [8:0] remap_result;
    logic [7:0] eff_opcode;
    logic       eff_is_0f;

    always_comb begin
        remap_result = microcode_group_remap(
            is_0f_prefix ? opcode_ext : opcode,
            is_0f_prefix,
            modrm_reg
        );
        eff_opcode = remap_result[7:0];
        eff_is_0f  = remap_result[8];
    end

    // =========================================================
    // ROM Lookup
    // =========================================================
    logic [14:0] rom_addr;
    assign rom_addr = {r_is_0f, r_opcode, r_step};

    logic [47:0] rom_data;
    assign rom_data = microcode_rom_lookup(rom_addr);

    // =========================================================
    // Micro-op Decode (combinational from ROM output)
    // =========================================================
    always_comb begin
        uop_data        = rom_data;
        uop_op_type     = op_type_t'(rom_data[UOP_OP_TYPE_HI:UOP_OP_TYPE_LO]);
        uop_alu_op      = rom_data[UOP_ALU_OP_HI:UOP_ALU_OP_LO];
        uop_dest_reg    = rom_data[UOP_DEST_REG_HI:UOP_DEST_REG_LO];
        uop_src_a_reg   = rom_data[UOP_SRC_A_REG_HI:UOP_SRC_A_REG_LO];
        uop_src_b_reg   = rom_data[UOP_SRC_B_REG_HI:UOP_SRC_B_REG_LO];
        uop_seg_reg     = rom_data[UOP_SEG_REG_HI:UOP_SEG_REG_LO];
        uop_special_cmd = rom_data[UOP_SPECIAL_HI:UOP_SPECIAL_LO];
        uop_immediate   = rom_data[UOP_IMM_HI:UOP_IMM_LO];
        uop_is_last     = rom_data[UOP_IS_LAST];
        uop_is_atomic   = rom_data[UOP_IS_ATOMIC];
    end

    // =========================================================
    // REP Termination Logic
    // =========================================================
    // REP_YIELD triggers a check: loop back to step 0 or complete.
    wire rep_yield_detected = (uop_special_cmd == UCMD_REP_YIELD);

    // REP terminates when:
    //   - ECX == 0 (after decrement in REP_STEP)
    //   - REPE (F3 with CMPS/SCAS): ZF == 0
    //   - REPNE (F2 with CMPS/SCAS): ZF == 1
    wire rep_terminate = rep_ecx_zero ||
                         (r_is_rep && !r_is_repne && !rep_zf_value) ||  // REPE: stop if ZF=0
                         (r_is_rep &&  r_is_repne &&  rep_zf_value);    // REPNE: stop if ZF=1

    // =========================================================
    // Sequencer FSM
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state      <= SEQ_IDLE;
            r_step     <= 6'd0;
            uop_valid  <= 1'b0;
            r_is_rep   <= 1'b0;
            r_is_repne <= 1'b0;
        end else if (flush) begin
            state      <= SEQ_IDLE;
            r_step     <= 6'd0;
            uop_valid  <= 1'b0;
            r_is_rep   <= 1'b0;
            r_is_repne <= 1'b0;
        end else begin
            case (state)
                SEQ_IDLE: begin
                    uop_valid <= 1'b0;
                    if (start) begin
                        r_opcode   <= eff_opcode;
                        r_is_0f    <= eff_is_0f;
                        r_step     <= 6'd0;
                        r_max_step <= microcode_max_step(eff_opcode, eff_is_0f);
                        r_atomic   <= microcode_is_atomic(eff_opcode, eff_is_0f);
                        r_is_rep   <= is_rep_prefix;
                        r_is_repne <= is_repne;
                        state      <= SEQ_ACTIVE;
                    end
                end

                SEQ_ACTIVE: begin
                    uop_valid <= 1'b1;
                    state     <= SEQ_STALL;
                end

                SEQ_STALL: begin
                    if (exec_ack) begin
                        // Check for REP_YIELD: loop or complete
                        if (rep_yield_detected && r_is_rep) begin
                            state <= SEQ_REP_CHECK;
                        end else if (uop_is_last || r_step >= (r_max_step - 6'd1)) begin
                            // Sequence complete
                            uop_valid <= 1'b0;
                            state     <= SEQ_IDLE;
                        end else begin
                            // Advance to next step
                            r_step    <= r_step + 6'd1;
                            state     <= SEQ_ACTIVE;
                        end
                    end
                end

                SEQ_REP_CHECK: begin
                    // REP loop iteration decision
                    if (rep_terminate) begin
                        // REP complete: finish sequence
                        uop_valid <= 1'b0;
                        state     <= SEQ_IDLE;
                    end else begin
                        // Loop back: restart from step 0 (skip REP_SETUP)
                        r_step    <= 6'd1;
                        state     <= SEQ_ACTIVE;
                    end
                end

                default: state <= SEQ_IDLE;
            endcase
        end
    end

endmodule
